### ISSUE TITLE
support for base String

### ISSUE THREAD

**Issue by matthewleon** [haskell-foundation/foundation-edge#3]
This would be helpful for working with libraries that still use the ugly `String` datatype.

For example, process: https://hackage.haskell.org/package/process-1.6.1.0

**Comment by vincenthz** [comment]
you can use the standard `fromList` which applied to `[Char]` will give you a foundation `String`. `toList` apply the inverse transformation. Also it works for all the array the same way. If that's not enough for what you want to do let me know, otherwise please close
